<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AskGamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ask_games')->delete();
        
        \DB::table('ask_games')->insert(array (
            0 => 
            array (
                'created_at' => '2022-09-01 08:17:09',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '18H30',
                'id' => 19,
                'place_of_game' => 'Ville-d\'Avray ',
                'status' => 'no_actions',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-09-22 11:30:18',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            1 => 
            array (
                'created_at' => '2022-09-01 10:15:17',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H30',
                'id' => 20,
                'place_of_game' => 'Marseille ',
                'status' => 'refused',
                'team_of_asker' => 'Marseille Foot',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-12-01 19:26:15',
                'who_is_asking' => 'Paris@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            2 => 
            array (
                'created_at' => '2022-09-01 10:18:28',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H45',
                'id' => 21,
                'place_of_game' => 'Lyon ',
                'status' => 'refused',
                'team_of_asker' => 'Paris Basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-09-23 10:58:44',
                'who_is_asking' => 'Paris@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            3 => 
            array (
                'created_at' => '2022-09-16 07:35:00',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '13H37',
                'id' => 22,
                'place_of_game' => 'Caen',
                'status' => 'pending',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Marseille Foot',
                'updated_at' => '2022-09-17 11:37:31',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Paris@gmail.com',
            ),
            4 => 
            array (
                'created_at' => '2022-09-16 12:58:02',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '22H15',
                'id' => 23,
                'place_of_game' => 'Lyon',
                'status' => 'pending-score',
                'team_of_asker' => 'Team-De-Basket',
                'team_of_who_was_asked' => 'Jamal basket',
                'updated_at' => '2022-09-24 11:12:18',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            5 => 
            array (
                'created_at' => '2022-09-24 13:53:55',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H53',
                'id' => 45,
                'place_of_game' => 'Paris',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-09-24 14:03:19',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            6 => 
            array (
                'created_at' => '2022-09-29 13:17:12',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H16',
                'id' => 48,
                'place_of_game' => 'Lyon',
                'status' => 'finish',
                'team_of_asker' => 'Jamal basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-09-29 13:20:19',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            7 => 
            array (
                'created_at' => '2022-09-29 13:22:01',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H21',
                'id' => 49,
                'place_of_game' => 'Paris stade',
                'status' => 'finish',
                'team_of_asker' => 'Jamal basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-09-29 13:23:15',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            8 => 
            array (
                'created_at' => '2022-09-29 13:25:38',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H25',
                'id' => 50,
                'place_of_game' => 'Montpellier ',
                'status' => 'finish',
                'team_of_asker' => 'Jamal basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-09-29 13:40:55',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            9 => 
            array (
                'created_at' => '2022-09-29 13:42:18',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H45',
                'id' => 51,
                'place_of_game' => 'Bordeaux ',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-09-29 13:44:11',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            10 => 
            array (
                'created_at' => '2022-09-30 09:07:46',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '15H30',
                'id' => 52,
                'place_of_game' => 'Paris saint germain ',
                'status' => 'finish',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-09-30 09:09:25',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            11 => 
            array (
                'created_at' => '2022-09-30 09:10:21',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '11H10',
                'id' => 53,
                'place_of_game' => 'Man',
                'status' => 'finish',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-09-30 09:12:05',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            12 => 
            array (
                'created_at' => '2022-09-30 09:39:27',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '11H39',
                'id' => 54,
                'place_of_game' => 'Paris',
                'status' => 'finish',
                'team_of_asker' => 'Team-De-Basket',
                'team_of_who_was_asked' => 'Jamal basket',
                'updated_at' => '2022-09-30 09:40:45',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            13 => 
            array (
                'created_at' => '2022-09-30 09:41:26',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '11H42',
                'id' => 55,
                'place_of_game' => 'Caen',
                'status' => 'finish',
                'team_of_asker' => 'Team-De-Basket',
                'team_of_who_was_asked' => 'Jamal basket',
                'updated_at' => '2022-09-30 09:42:43',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            14 => 
            array (
                'created_at' => '2022-10-01 19:41:57',
                'date_of_game' => '2022-10-06 18:27:49',
                'hours_of_game' => '21H41',
                'id' => 56,
                'place_of_game' => 'Paris',
                'status' => 'finish',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-10-01 19:43:37',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            15 => 
            array (
                'created_at' => '2022-10-01 19:45:47',
                'date_of_game' => '2022-10-06 18:28:04',
                'hours_of_game' => '21H45',
                'id' => 57,
                'place_of_game' => 'Paris',
                'status' => 'pending',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-10-01 19:45:47',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            16 => 
            array (
                'created_at' => '2022-10-06 08:34:50',
                'date_of_game' => '2022-04-15 02:20:58',
                'hours_of_game' => '19h30',
                'id' => 101,
                'place_of_game' => 'New Guillermo',
                'status' => 'finish',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-10-06 08:34:50',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            17 => 
            array (
                'created_at' => '2022-10-06 08:34:50',
                'date_of_game' => '2022-03-14 13:57:11',
                'hours_of_game' => '19h30',
                'id' => 102,
                'place_of_game' => 'Erdmanville',
                'status' => 'finish',
                'team_of_asker' => 'Jamal Foot',
                'team_of_who_was_asked' => 'Real Team',
                'updated_at' => '2022-10-06 08:34:50',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            18 => 
            array (
                'created_at' => '2022-10-06 11:15:32',
                'date_of_game' => '2022-05-27 06:02:49',
                'hours_of_game' => '19h30',
                'id' => 103,
                'place_of_game' => 'South Carmine',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-10-06 11:15:32',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            19 => 
            array (
                'created_at' => '2022-10-06 11:15:32',
                'date_of_game' => '2022-07-07 10:06:35',
                'hours_of_game' => '19h30',
                'id' => 104,
                'place_of_game' => 'South Jett',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-10-06 11:15:32',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            20 => 
            array (
                'created_at' => '2022-10-06 11:23:47',
                'date_of_game' => '2022-11-26 09:06:52',
                'hours_of_game' => '19h30',
                'id' => 105,
                'place_of_game' => 'Homenickfurt',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-10-06 11:23:47',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            21 => 
            array (
                'created_at' => '2022-10-06 11:23:47',
                'date_of_game' => '2022-12-02 18:00:01',
                'hours_of_game' => '19h30',
                'id' => 106,
                'place_of_game' => 'Enolamouth',
                'status' => 'finish',
                'team_of_asker' => 'Real Team',
                'team_of_who_was_asked' => 'Jamal Foot',
                'updated_at' => '2022-10-06 11:23:47',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            22 => 
            array (
                'created_at' => '2022-12-19 11:40:07',
                'date_of_game' => '2022-12-30 11:39:14',
                'hours_of_game' => '12H45',
                'id' => 107,
                'place_of_game' => 'Paris stade',
                'status' => 'finish',
                'team_of_asker' => 'Team-De-Basket',
                'team_of_who_was_asked' => 'Jamal basket',
                'updated_at' => '2022-12-20 10:22:03',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            23 => 
            array (
                'created_at' => '2022-12-19 13:27:04',
                'date_of_game' => '2022-12-21 13:26:00',
                'hours_of_game' => '16H30',
                'id' => 108,
                'place_of_game' => 'New match stade',
                'status' => 'finish',
                'team_of_asker' => 'Jamal basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-12-19 13:30:21',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            24 => 
            array (
                'created_at' => '2022-12-19 15:07:01',
                'date_of_game' => '2022-12-19 15:06:39',
                'hours_of_game' => '18H6',
                'id' => 109,
                'place_of_game' => 'Mon stade ',
                'status' => 'finish',
                'team_of_asker' => 'Jamal basket',
                'team_of_who_was_asked' => 'Team-De-Basket',
                'updated_at' => '2022-12-19 15:08:12',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            25 => 
            array (
                'created_at' => '2023-01-16 19:31:15',
                'date_of_game' => '2023-01-16 19:31:02',
                'hours_of_game' => '20H35',
                'id' => 110,
                'place_of_game' => 'Babines ',
                'status' => 'finish',
                'team_of_asker' => 'Jimmy handball',
                'team_of_who_was_asked' => 'jamal hand',
                'updated_at' => '2023-01-16 19:33:14',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
            26 => 
            array (
                'created_at' => '2023-01-19 15:54:28',
                'date_of_game' => '2023-01-27 15:54:00',
                'hours_of_game' => '16H54',
                'id' => 111,
                'place_of_game' => 'Babi',
                'status' => 'finish',
                'team_of_asker' => 'jamal hand',
                'team_of_who_was_asked' => 'Jimmy handball',
                'updated_at' => '2023-01-19 17:41:30',
                'who_is_asking' => 'Jamal@gmail.com',
                'who_was_asked' => 'jbull635@gmail.com',
            ),
            27 => 
            array (
                'created_at' => '2023-01-19 18:15:28',
                'date_of_game' => '2023-01-28 18:14:55',
                'hours_of_game' => '19H14',
                'id' => 112,
                'place_of_game' => 'paris stade',
                'status' => 'finish',
                'team_of_asker' => 'Jimmy handball',
                'team_of_who_was_asked' => 'jamal hand',
                'updated_at' => '2023-01-19 18:17:18',
                'who_is_asking' => 'jbull635@gmail.com',
                'who_was_asked' => 'Jamal@gmail.com',
            ),
        ));
        
        
    }
}